import type { AssetDefinition } from "../types";

export const ASSETS: AssetDefinition[] = [
  {
    symbol: "BTCUSDT",
    displayName: "Bitcoin",
    class: "crypto",
    startPrice: 64000,
    vol: 0.0032,
    seed: 101,
    logo: "B",
  },
  {
    symbol: "ETHUSDT",
    displayName: "Ethereum",
    class: "crypto",
    startPrice: 3200,
    vol: 0.0042,
    seed: 102,
    logo: "E",
  },
  {
    symbol: "SOLUSDT",
    displayName: "Solana",
    class: "crypto",
    startPrice: 150,
    vol: 0.006,
    seed: 103,
    logo: "S",
  },
  {
    symbol: "BNBUSDT",
    displayName: "Binunce Coin",
    class: "crypto",
    startPrice: 580,
    vol: 0.0038,
    seed: 104,
    logo: "N",
  },
  {
    symbol: "DOGEUSDT",
    displayName: "Dogecoin",
    class: "crypto",
    startPrice: 0.13,
    vol: 0.009,
    seed: 105,
    logo: "D",
  },
  {
    symbol: "PEPEUSDT",
    displayName: "Pepe",
    class: "crypto",
    startPrice: 0.0000098,
    vol: 0.017,
    seed: 106,
    logo: "P",
  },
  {
    symbol: "XRPUSDT",
    displayName: "XRP",
    class: "crypto",
    startPrice: 0.52,
    vol: 0.0072,
    seed: 107,
    logo: "X",
  },
  {
    symbol: "ADAUSDT",
    displayName: "Cardano",
    class: "crypto",
    startPrice: 0.41,
    vol: 0.0064,
    seed: 108,
    logo: "A",
  },
  {
    symbol: "AAPL",
    displayName: "Apple",
    class: "stock",
    startPrice: 225,
    vol: 0.0015,
    seed: 201,
    logo: "A",
  },
  {
    symbol: "TSLA",
    displayName: "Tesla",
    class: "stock",
    startPrice: 250,
    vol: 0.0046,
    seed: 202,
    logo: "T",
  },
  {
    symbol: "NVDA",
    displayName: "Nvidia",
    class: "stock",
    startPrice: 130,
    vol: 0.0038,
    seed: 203,
    logo: "N",
  },
  {
    symbol: "AMZN",
    displayName: "Amazon",
    class: "stock",
    startPrice: 190,
    vol: 0.0022,
    seed: 204,
    logo: "Z",
  },
  {
    symbol: "MSFT",
    displayName: "Microsoft",
    class: "stock",
    startPrice: 460,
    vol: 0.0018,
    seed: 205,
    logo: "M",
  },
  {
    symbol: "GME",
    displayName: "GameStop",
    class: "stock",
    startPrice: 25,
    vol: 0.012,
    seed: 206,
    logo: "G",
  },
];

export const DEFAULT_SYMBOL = "BTCUSDT";

export function getAsset(symbol: string): AssetDefinition {
  return ASSETS.find((asset) => asset.symbol === symbol) ?? ASSETS[0];
}
